#env.deployment=prod
env.deployment=dev
splitter.minLength = 0;
splitter.maxLength = 1000;
splitter.overlap = 200;
splitter.boundary = "paragraph";
splitter.delimiters = " ";
system.require.regconfirmation=false
app.webhook.url=http://localhost:9080/hub/web-hook
app.sql.webhook.url=http://localhost:9080/hub/web-hook-query
#database.platform.name=MYSQL
database.platform.name=HSQLDB
#database.platform.name=POSTGRESQL
platform.schema=skillhub
orchestration.enabled=false
show.roles.as.debug=true
app.context=skillhub
sms.endpoint.url=direct://send-sms
email.endpoint.url=direct://send-email
uploads.incoming.file.dir=/opt/app-data/hub/incoming
app.items.per.page=2
polygon.api.key=egNEPQUUkqpKnnR6aeTQBmcBpYOqWOOE
applicationId=Skill Hub
brand=Skill Hub
country=Zimbabwe
system.available.countries=Zimbabwe
current.country.initials=zw
app.script.dir=/js
platform.active.model=deepseek-r1
platform.language.service.option=mock
#platform.language.service.option=ollama
platform.ollama.host=http://localhost/ollama:11434
dynamicimagesbaseurl=http://localhost:9080/hub/web/download-attachment
orgId=MaroTech
yahoo.finance.url=https://query1.finance.yahoo.com/v8/finance/chart/%s?region=US&lang=en-US&includePrePost=false&interval=2m&useYfid=true&range=1d&corsDomain=finance.yahoo.com&.tsrc=finance
dataDurationAllowedInSeconds=18000
app.platform=basic
associations=FIFA,UEFA,CONMEBOL,ZIFA,AFCON,AFC,CONCACAF,OFC,NBA,NFL,NHL
platform.models=deepseek-r1:1.3b,deepseek-r1:1.5b,deepseek-r1:8b,deepseek-r1:14b,\
deepseek-llm,\
deepseek-coder,\
openchat,\
gemma,\
gemma2,\
llama2,\
llama3,\
llama3.1,\
mistral,\
mixtral,\
llava,\
llava-phi3,\
neural-chat,\
codellama,\
dolphin-mixtral,\
mistral-openorca,\
llama2-uncensored,\
phi,\
phi3,\
orca-mini,\
dolphin-mistral,\
vicuna,\
wizard-vicuna-uncensored,\
zephyr,\
openhermes,\
qwen,\
qwen2,\
wizardcoder,\
llama2-chinese,\
tinyllama,\
phind-codellama,\
orca2,\
falcon,\
wizard-math,\
tinydolphin,\
nous-hermes,\
yi,\
dolphin-phi,\
starling-lm,\
starcoder,\
codeup,\
medllama2,\
stable-code,\
wizardlm-uncensored,\
bakllava,\
everythinglm,\
solar,\
stable-beluga,\
sqlcoder,\
yarn-mistral,\
nous-hermes2-mixtral,\
samantha-mistral,\
stablelm-zephyr,\
meditron,\
wizard-vicuna,\
stablelm2,\
magicoder,\
yarn-llama2,\
nous-hermes2,\
llama-pro,\
open-orca-platypus2,\
codebooga,\
mistrallite,\
nexusraven,\
goliath,\
nomic-embed-text,\
notux,\
alfred,\
megadolphin,\
wizardlm,\
xwinlm,\
notus,\
duckdb-nsql,\
all-minilm,\
codestral